### PR TITLE
Adds timezone to "meetup time in local time" display.

### PR DESCRIPTION
**Pull request by damncabbage**
(PRing the change I requested in this thread: https://twitter.com/damncabbage/status/828211451441537024)

### CODE REVIEW

**Comment by soupi** [comment]
Hi, thanks for the PR!

I'm currently not on my computer so I'll only be able to review this properly later, but does this just add something like +0200 (in my case) to the datetime string?

Can you explain what you thought the date time string meant? I thought not including a timezone means local time.

I think this addition might be a bit confusing in its current form, i might need to ask around and see if more people found the current string with no timezone confusing as well.

**Comment by soupi** [comment]
After talking about this with someone else I'm now convinced. But could you perhaps change the format string to add something like `(UTCZZ)` instead of just `ZZ`? (also, does that make sense?)

**Comment by damncabbage** [comment]
I get what you mean, but I think that means formatting the string twice, eg.
```js
var time = moment.utc(original, 'YYYY-MM-DD HH:mm').local();
dt.innerHTML = time.format("dddd, MMMM Do YYYY, h:mm a") + " UTC" + time.format("ZZ");
```

If you're happy with that, I can make the change.

**Comment by soupi** [comment]
I have tested changing line 7:

```js
dt.innerHTML = moment.utc(dt.innerHTML.slice(0, -6), 'YYYY-MM-DD HH:mm').local().format("dddd, MMMM Do YYYY, h:mm a");
```

to:

```js
dt.innerHTML = moment.utc(dt.innerHTML.slice(0, -6), 'YYYY-MM-DD HH:mm').local().format("dddd, MMMM Do YYYY, h:mm a (UTCZZ)");
```

And I get the addition: `(UTC+0200)` properly. Is there a reason this shouldn't work?

Actually, I'm also not sure what this does and why it is necessary:

```js
dt.setAttribute("data-utc-time", original);
```

Sorry, My JS-foo is fairly poor.

**Comment by damncabbage** [comment]
Oh! I didn't know you could do that sorry.

I chucked the original time on an attribute so people digging could see what the original time was converted from, but this is mostly soothing my own regularly-dealing-with-timezone-stuff-ups paranoia; I can remove it.

**Comment by soupi** [comment]
yes please :) I can also do this myself if you prefer that.

edit: you know what, i don't mind keeping it much.

**Comment by damncabbage** [comment]
Altered and pushed.

**Comment by soupi** [comment]
Thanks!

**Pull request merged**
