### PR TITLE
WIP: Add procfile

### PR DESCRIPTION
**Pull request by chexxor**
I haven't got this working yet, but I want to create a thread to discuss this effort.

I installed the heroku tools, then ran the following commands to deploy and check the result.

``` sh
$ heroku create --buildpack https://github.com/mfine/heroku-buildpack-stack.git
$ heroku apps:rename soupi-gathering
$ heroku buildpacks:set https://github.com/mfine/heroku-buildpack-stack
$ git push heroku master
# Open https://soupi-gathering.herokuapp.com/ in browser
$ heroku logs -a soupi-gathering
# Newest logs at bottom.
2017-01-22T19:03:40.211252+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/"
```

I don't know what command to run to run the app. We need to put that command in the Procfile's "web"  key, as that's the process to which Heroku sends HTTP requests from its load-balancer.

### CODE REVIEW

**Comment by soupi** [comment]
This repo is probably not the right place for specific configurations. Perhaps it'll be better to use your fork ([chexxor/gathering](/chexxor/gathering)) as the repo?

**Comment by chexxor** [comment]
Yeah, that's fine.

**Comment by chexxor** [comment]
Here's the latest progress, with your help. We can continue later. Thanks so much!

``` sh
2017-01-22T23:32:18.818216+00:00 heroku[web.1]: State changed from crashed to starting
2017-01-22T23:32:20.498771+00:00 heroku[web.1]: Starting process with command `/app/.local/bin/gather --port=43952`
2017-01-22T23:32:22.681570+00:00 heroku[web.1]: Process exited with status 1
2017-01-22T23:32:22.614035+00:00 app[web.1]: Invalid option `--port=43952'
2017-01-22T23:32:22.614083+00:00 app[web.1]:
2017-01-22T23:32:22.615661+00:00 app[web.1]: Usage: gather [-f|--config FILE] [-t|--title NAME] [-D|--description DESC]
2017-01-22T23:32:22.616855+00:00 app[web.1]:               [-d|--domain Domain] [-c|--dbconn DBCONN] [COMMAND]
2017-01-22T23:32:22.696994+00:00 heroku[web.1]: State changed from starting to crashed
2017-01-22T23:32:48.078724+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=soupi-gathering.herokuapp.
com request_id=dac18b53-5859-46a3-abaa-06bacb778b68 fwd="184.100.87.223" dyno= connect= service= status=503 bytes=
```

**Comment by soupi** [comment]
Oh right. I think it should be `../gather http --port $PORT`

**Comment by chexxor** [comment]
That fixed it - now it starts the process and displays "500 - Internal Server Error \n\n powered by Spock" in my browser. Probably an error in connecting to postgres.

**Comment by chexxor** [comment]
Nice! I've got a heroku postgres db connected to it. New error message when loading in browser. `ResultError (ServerError "42P01" "relation \"events\" does not exist" Nothing Nothing)`

**Comment by chexxor** [comment]
Got it up!
https://soupi-gathering.herokuapp.com/

**Comment by chexxor** [comment]
I addition to the commands in the original post, these commands were also necessary:

``` sh
$ heroku ps:scale web=1
$ heroku addons:create heroku-postgresql:hobby-dev
# Get DB string using `heroku pg:credentials`
# User and pass and DB are all strings of random numbers.
$ psql -U $USER_FROM_DB_URL-d $DB_FROM_DB_URL -p $PORT_FROM_DB_URL -f database_scripts/gather.ddl
# Init database from local machine. I was only able to connect using psql using the heroku command, like this.
$ cat database_scripts/database.ddl | heroku pg:psql  --app soupi-gathering
```

**Comment by chexxor** [comment]
Closing, as you've found a cheap host for the app, and it's now hosted at gathering.purescript.org.

**Pull request closed without merging**
